### ISSUE TITLE
ER diagramformat not work

### ISSUE THREAD

**Issue by gaozhidf** [k1LoW/tbls#119]
Version: v1.16.0
System: Ubuntu 18.04

add `ER` config into `.tbls.yml`, but it still generates png file ??
```
er:
  # Skip generation of ER diagram
  # Default is false
  skip: false
  # ER diagram format
  # Default is `png`
  format: svg
```

ps: tbls is a great tool !!!
