### ISSUE TITLE
Add a command-line switch to either tbls out or tbls lint to ignore virtual information

### ISSUE THREAD

**Issue by mjpieters** [k1LoW/tbls#208]
### What happened

I'm dealing with slow connection to a remote database; running `tbls lint` or `tbls doc` over an ssh tunnel is painfully slow. However, running `tbls` on the remote server and then outputting to JSON back over the SSH connection is *way* better:

```bash
alias rtbls="scp .tbls.yml server:/tmp && ssh server 'cd /tmp && tbls out -t json' > /tmp/tbls.json"
rtbls && tbls lint json:///tmp/tbls.json
```

However, I'm defining additional `relations:` entries in my configuration:

```yaml
# additional implied relationships
relations:
  - table: foo
    columns:
      - bar_type
    parentTable: bar_types
    parentColumns:
      - bar_type_name
    def: bar_type validation
   - table: bar_types
     columns:
       - spamparams
     parentTable: spam_definitions
     parentColumns:
       - name
     def: validation of `spam?ham=...` parameters

lint:
  duplicateRelations:
    enabled: true
 ```

These are reflected in the exported JSON file in the `"relations"` structure with `"virtual": true`set.

When you then run `lint` with the same configuration file and the JSON file as the DSN, warnings are generated for duplicate relationships:

```
public.foo: duplicate relations. [public.foo -> public.bar_types]
public.bar_types: duplicate relations. [public.foo -> public.spam_definitions]
```

When generating ER diagrams, **two** dotted lines and labels are drawn, per virtual relationship.

### What you expected to happed

Virtual relationships present in the configuration file and in a JSON dump should be merged, and so not generate a warning or a duplicate line.

### Anything else we need to know?

Workaround is to remove the `"virtual": true` relationships first; using `jq` as a filter:

```bash
"... && ssh server '...' | jq 'del(.relations[] | select(.virtual == true))' > /tmp/tbls.json"
```
This problem may also apply to comments defined in the configuration. I did not test this.

### Environment

- `tbls version`: 1.35.0
- Database version: Postgresql 10
- OS: Ubuntu 18.04 (remote server) & Mac OS X 10.13 (local machine driving the ssh connection)
- Shell: `bash`
