### ISSUE TITLE
Invalid links can be generated when not selecting all the tables 

### ISSUE THREAD

**Issue by palucki** [k1LoW/tbls#223]
### What happened

Suppose you have tables A, B, and C.
both A and B point to table C.
If we specify to generate docs only for tables A and B, the link in theese pointing to non existing table C documentation will be generated.

### What you expected to happed

Should not create a link to avoid user errors when browsing generated output.
A switch not to generate links at all can do the job as well.

### Environment

* tbls version : 1.37.0
* postgreSQL database
* Windows 10
* config:
```
comments:
- table: A
  tableComment: table A
- table: B
  tableComment: table B
desc: 'My description'
docPath: doc/schema
dsn: postgres://user:pass@localhost:5432/dbname?sslmode=disable
er:
  skip: true
include:
- A
- B
name: Db overview
```
