### ISSUE TITLE
Plantuml ER diagrams empty

### ISSUE THREAD

**Issue by AltarBeastiful** [k1LoW/tbls#304]
### What happened
Trying to generate plantuml ER diagrams from a mysql db with comments using `tbls doc` and my config : 
```
dsn: mysql://xxx:xxx@localhost:3306/xxx
docPath: doc/

include:
  - def_*
exclude:
  - produit_*

er:
  skip: false
  format: plantuml
  comment: true
```

This generates empty `.plantuml` files for table and global schema.
Tried using `format: puml` but getting empty `.puml` files.

I'm able to generate the global schema using `tbls out -c tbls.yml -t plantuml -o schema.puml`
But my table comments are not added to the generated .puml file.
Am I missing something in the configuration ? 

### Sidenote
If I enter any format in `config.ER.format`, it will generate empty files with the format entered. I guess there is no check on the format config entry?

### Environment

- `1.50`
- MySQL 5.5
- Windows 10
- Cmder
- _Tried to set DEBUG=1 but got not additional messages_
