### ISSUE TITLE
include/exclude of table columns

### ISSUE THREAD

**Issue by bakhoraliev** [k1LoW/tbls#305]
Hi, could you add a feature, that allows filter table columns.

How it can be realized in `.tbls.yml`:
```yaml
columns:
  -
    table: users
    exclude: 
      - created
      - updated
  
  -
    table: posts
    include:
      - id
      - user_id
      - title
      - body
```
! DB tables are taken from `https://github.com/k1LoW/tbls/tree/master/sample/sqlite`
