### ISSUE TITLE
Exclude all tables except specific table

### ISSUE THREAD

**Issue by FelixZY** [k1LoW/tbls#369]
I have a database where I want to exclude all tables from the `auth` schema, except `auth.users`. This database also has tables in other schemas that I want to be included.

I tried
```yaml
# .tbls.yml
include:
  - * # also `"*"`, `'*'`, `"**/*"` as well as removing this line
  - auth.users
exclude:
  - auth.*
```

However, this causes all output to be excluded, producing an empty output.
1. How can I exclude all tables in the `auth` schema, except `auth.users`?
2. How can I include all other tables when using an `include` section? (`*` does not seem to work when used alone)

### Environment

- `tbls 1.56.2`
- OS `Debian bullseye`
- Shell `bash`
