### ISSUE TITLE
Unable to filter schemas using include/exclude for PostgreSQL DB

### ISSUE THREAD

**Issue by Bare7aOVO** [k1LoW/tbls#389]
### What happened
tbls is always generating all of the tables in all schemas instead of the ones for the specified in the include/exclude filters provided at the end of the ticket

### What you expected to happened
I expect tbls to generate only the lint and er for the `public` schema, excluding all of the tables from the `products` schema

### Environment

- tbls version `1.56.8`
- Database version `13`
- OS `WSL2`
- Shell `zsh`
- Config:

Tried with:

```YAML
include:
  - public
```

```YAML
include:
  - public.
```

```YAML
include:
  - public.*
```

```YAML
include:
  - public.*
exclude:
  - products.*
```

```YAML
include:
  - public.*
exclude:
  - products.
```

```YAML
include:
  - public.
exclude:
  - products.*
```

```YAML
include:
  - public
exclude:
  - products
```

```YAML
include:
  - public.*
exclude:
  - products
```

```YAML
include:
  - public
exclude:
  - products.*
```
