### ISSUE TITLE
Publish GitHub action to marketplace

### ISSUE THREAD

**Issue by FelixZY** [k1LoW/tbls#405]
Have you considered releasing an official [GitHub action to the actions marketplace](https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace)? This would make tbls even easier to use in GitHub-based CI flows.

**Comment by k1LoW** [comment]
@FelixZY Thank you for your request.

I think it would be better to have tbls-action. However, there are many things to consider in providing it, so I have no immediate plans to create it.

- Only `tbls doc` commands ?
- Difficult to resolve hostnames when connecting to database if provided by Docker action.
- Support for Windows

**Comment by FelixZY** [comment]
I was mostly thinking an action to cover the [install section](https://github.com/k1LoW/tbls#install) of the readme. Currently, I do this:

```yaml
        - name: Install [tbls](https://github.com/k1LoW/tbls)
        run: |
          curl -sL https://github.com/k1LoW/tbls/releases/download/v${TBLS_VERSION}/tbls_${TBLS_VERSION}-1_amd64.deb --output /tmp/tbls.deb
          sudo dpkg -i /tmp/tbls.deb
```

But I was thinking something like this would be nice:

```yaml
      - uses: k1LoW/setup-tbls@v1
        with:
          version: ${{ env.TBLS_VERSION }}
```
