### ISSUE TITLE
Support of old MSSQL versions

### ISSUE THREAD

**Issue by usmanovbf** [k1LoW/tbls#478]
### What happened
```
mssql: 'STRING_AGG' is not a recognized built-in function name.
```
### What you expected to happened
to generate doc for mssql db
### What stack trace or error message from tbls did you see?
see below
### Anything else we need to know?
It is a huge world of old database versions, so it can be important for you, I guess, to step into that world
### Environment

- `tbls version`
./tbls version
1.65.3

- Database version
DBMS: Microsoft SQL Server (ver. 13.00.5337)
Case sensitivity: plain=mixed, delimited=mixed
Driver: Microsoft JDBC Driver 12.2 for SQL Server (ver. 12.2.0.0, JDBC4.2)
- OS ( `Ubuntu bionic`, `macOS Calalina`, `WSL2`, etc )
macOs Catalina
- Shell ( `bash`, `zsh`, `poworshell`, etc )
zsh
- Stacktrace or error message from tbls ( If you can, set `DEBUG=1`)
```
DEBUG=1 ./tbls doc sqlserver://...
mssql: 'STRING_AGG' is not a recognized built-in function name.
github.com/k1LoW/tbls/drivers/mssql.(*Mssql).Analyze
        /Users/runner/work/tbls/tbls/drivers/mssql/mssql.go:177
github.com/k1LoW/tbls/datasource.Analyze
        /Users/runner/work/tbls/tbls/datasource/datasource.go:131
github.com/k1LoW/tbls/cmd.glob..func5
        /Users/runner/work/tbls/tbls/cmd/doc.go:72
github.com/spf13/cobra.(*Command).execute
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916
github.com/spf13/cobra.(*Command).ExecuteC
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044
github.com/spf13/cobra.(*Command).Execute
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/k1LoW/tbls/cmd.Execute
        /Users/runner/work/tbls/tbls/cmd/root.go:194
main.main
        /Users/runner/work/tbls/tbls/main.go:34
runtime.main
        /Users/runner/hostedtoolcache/go/1.19.8/x64/src/runtime/proc.go:250
runtime.goexit
        /Users/runner/hostedtoolcache/go/1.19.8/x64/src/runtime/asm_amd64.s:1594
```
- Config ( .tbls.yml )
```
docPath: doc/schema

er:
  # Skip generation of ER diagram
  # Default is false
  skip: false
  # ER diagram image format
  # Default is `svg`
  format: png
  # Add table/column comment to ER diagram
  # Default is false
  comment: true
  # Distance between tables that display relations in the ER
  # Default is 1
  distance: 1
  # Hide relation definition from ER diagram
  # Default is false
  hideDef: true
```
