### ISSUE TITLE
add comment

### ISSUE THREAD

**Issue by thimi0412** [k1LoW/tbls#48]
```
comments:
    -
        table: a
        comment: xxxxxxxxxxxxxxxxxxxxx
        columnComments:
            order_no: xxxxxxxx
            detail_no: xxxxxxxxx
            amazon_item_id: xxxxxxxx
            divided_delivery_charge: xxxxxxxxx
            divided_cod_fee: xxxxxxxxx
            registration_date: xxxxxxxxx
            registration_id: xxxxxxxxx
            update_date: xxxxxxxxx
            update_id: xxxxxxxxx
    -
        table: b
        comment: xxxxxxxxx
        columnComments:
            order_no: xxxxxxxxx
            store_code: xxxxxxxxx
            course: xxxxxxxxx
            registration_date: xxxxxxxxx
            registration_id: xxxxxxxxx
            update_date: xxxxxxxxx
            update_id: xxxxxxxxx
```
以上のようにymlファイルを記述しましたがコメントが追加されません
しかしテーブルを１つだけ指定した場合は追加されます
2個目の-(ハイフン)を無くしても追加されませんでした
