### ISSUE TITLE
Enable to name Viewpoint files instead of indexes

### ISSUE THREAD

**Issue by majimaccho** [k1LoW/tbls#591]
Hi. Big thank you as always for tbls and maintaining it.

It could be nicer if we can set custom names on each viewpoints.

This is because when I want to insert a new viewpoint above a existing viewpoint, all viewpoints under the new one renamed.

For example, when we have viewpoints like below,
```
viewpoint-1.md
viewpoint-2.md
viewpoint-3.md
.
.
.
viewpoint-n.md

```

then add add a new viewpoint right under viewpoint 1, all viewpoints below viewpoint 2 get renamed like below.
```
viewpoint-1.md
viewpoint-2.md <- new viewpoint
viewpoint-3.md <- previous viewpoint 2
viewpoint-4.md <- previous viewpoint 3
.
.
.
viewpoint-n+1.md <- previous viewpoint n
```

When viewpoint  tbls.yaml would look like this.

```yaml
 .tbls.yml

viewpoints:
  -
    name: comments on post
    id: comments-on-post # <- This should create `viewpoint-comments-on-post.md`
    desc: Users can comment on each post multiple times and put a star on each comment.
    tables:
      - users

```

I'm not sure `id` is the best name for this feature.
If you have better naming or specs, I'm happy to listen to them. 
Thank you again!
