### ISSUE TITLE
Error when referencing itsself

### ISSUE THREAD

**Issue by uvulpos** [k1LoW/tbls#593]
### What happened
I have a database with a role. A role can inherit from another role. Like for example the role chef inherits permissions from the role cook like using_knife or use_stove. But chef also have additional roles like buy_groceries. When cook gets a new role, chef should get it too. So I have a reference to itself

### What you expected to happened
An arrow on the side to itself. Maybe even colorful to see its referencing to itsself. But not bothering other innocent tables

### What stack trace or error message from tbls did you see?
none.

### Anything else we need to know?
<img width="491" alt="Screenshot 2024-06-08 at 00 15 48" src="https://github.com/k1LoW/tbls/assets/53957681/405ed4c2-f692-45bb-be48-89090001bd7e">

### Environment

- `tbls version`: 1.76.0
- Database version: postgres latest
- OS `macOS Sonomo... something`
- Config ( .tbls.yml ):

```yaml
# .tbls.yml

# DSN (Database Source Name) to connect database
dsn: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable

# Path to generate document
# Default is `dbdoc`
docPath: ./doc/schema

include:
   - public.*
```
