### ISSUE TITLE
er.showColumnTypes.related/primary are ignored If include is set and number of result tables are less than input schema

### ISSUE THREAD

**Issue by shellyln** [k1LoW/tbls#685]
### What happened
When filtering tables in the input schema with `include` in `.tbls.yml`, the `er.showColumnTypes.related/primary` setting to hide columns other than PK and FK in the ER diagram output no longer works.
When I wrote all tables in the input schema in the `include` (even with wildcards), the problem did not occur.

### What you expected to happened
I expect that even if `include` is set, columns other than PK and FK will be hidden in the same way as if it were not set.

### Environment

- `tbls version`
  - `1.85.0`
- Database version
  - json DSN
- OS ( `Ubuntu bionic`, `macOS Calalina`, `WSL2`, etc )
  - `Windows 11`
- Shell ( `bash`, `zsh`, `poworshell`, etc )
  - `poworshell`
- Stacktrace or error message from tbls ( If you can, set `DEBUG=1`)
- Config ( .tbls.yml )

```yml
# .tbls.yml
dsn: json://schema.json

docPath: doc/schema

format:
  # Adjust the column width of Markdown format table
  # Default is false
  adjust: false
  # Sort the order of table list and columns
  # Default is false
  sort: true
  # Display sequential numbers in table rows
  # Default is false
  number: false
  # The comments for each table in the Tables section of the index page will display the text up to the first double newline (first paragraph).
  # Default is false
  showOnlyFirstParagraph: false
  # Hide table columns without values
  # Default is false
  hideColumnsWithoutValues: false
  # It can be boolean or array
  # hideColumnsWithoutValues: ["Parents", "Children"]

er:
  # Skip generation of ER diagram
  # Default is false
  skip: false
  # ER diagram image format (`png`, `jpg`, `svg`, `mermaid`)
  # Default is `svg`
  format: mermaid
  # Add table/column comment to ER diagram
  # Default is false
  comment: false
  # Hide relation definition from ER diagram
  # Default is false
  hideDef: false
  # Show column settings in ER diagram. If this section is not set, all columns will be displayed (default).
  showColumnTypes:
    # Show related columns
    related: true
    # Show primary key columns
    primary: true
  # Distance between tables that display relations in the ER
  # Default is 1
  distance: 2
  # ER diagram (png/jpg) font (font name, font file, font path or keyword)
  # Default is "" (system default)
  font:

include:
  - Account
  - Contact
```
schema.json
```json
{
    "tables": [
        {
            "name": "Account",
            "type": "Standard object",
            "columns": [
                {
                    "name": "Id",
                    "type": "Id",
                    "nullable": false,
                    "comment": "Id"
                },
                {
                    "name": "Foo",
                    "type": "Text",
                    "nullable": false,
                    "comment": "Foo"
                }
            ]
        },
        {
            "name": "Product2",
            "type": "Standard object",
            "columns": [
                {
                    "name": "Id",
                    "def": "Primary Key",
                    "table": "Product2",
                    "columns": [
                        "Id"
                    ]
                }
            ]
        },
        {
            "name": "Contact",
            "type": "Standard object",
            "columns": [
                {
                    "name": "Id",
                    "type": "Id",
                    "nullable": false,
                    "comment": "Id"
                },
                {
                    "name": "Bar",
                    "type": "Text",
                    "nullable": false,
                    "comment": "Bar"
                }
            ]
        }
    ],
    "driver": {
        "name": "",
        "database_version": ""
    }
}
```

#### memo
Isn't `len(cc.ChildRelations) > 0 || len(cc.ParentRelations) > 0` correct?
https://github.com/k1LoW/tbls/blob/adffc6347812bf2f0d5cd7e18f8ec8900df91770/config/config.go#L594-L605
https://github.com/k1LoW/tbls/blob/adffc6347812bf2f0d5cd7e18f8ec8900df91770/schema/filter.go#L110-L125
