### ISSUE TITLE
Markdown code block gets masked inside of table containing column comments

### ISSUE THREAD

**Issue by akelsch** [k1LoW/tbls#710]
Hi,

since [v1.85.1](https://github.com/k1LoW/tbls/releases/tag/v1.85.1) which includes https://github.com/k1LoW/tbls/pull/687 to fix https://github.com/k1LoW/tbls/issues/686 we can no longer use Markdown syntax highlighting for column comments.

For example:

```yaml
comments:
  - table: my_table
    tableComment: |
      This is the table comment.
    columnComments:
      id: This is the id column comment, I want to use `code` syntax highlighting here.
```

Previously it would not touch the backticks but now they get escaped so we literally get \`code\` instead of `code` (highlighted).

Am I missing something or is this intentional? Escaping the backticks using backslash did not work unfortunately. For now we can rollback to v1.85.0 of course but it would be nice for it to work in current versions.

Thanks!
